NFT-DAO/Governance-HOLON

CODE_OF_CONDUCT.md

Based upon the following GitHub standard guidelines : https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

Created Draft Code Of Conduct

---

Contribute.md

Removed .md from Contribute.md text heading

Removed .md from Contribute.md

---

README.md

Added "Genesis of the Governance HOLON GitHub" text

Added Genesis of the Governance HOLON GitHub

---

README.md

Added Contribution text to README.md

Added Contribution text

---

Documents/maintainer-message.md

Added Activity link and Thank-you

Added Activity link

---

Documents/maintainer-message.md

Added Formatting Changes, Markdown Headers. Corrected Spelling.

Formatting Changes

---

Documents/maintainer-message.md

Formatting change - capital Header

Formatting change

---

README.md

Link to intro message

---

CODE_OF_CONDUCT.md

Replaced by the term **Key HOLONs (TBA)**

Removed Reference to Community Leaders

---

CODE_OF_CONDUCT.md

Removed Reference to "permanent ban"

---

Business-Plan/05-Our-Values/Documents/Charter/Draft-Charter.md

Added Boilerplate text to get the content going.

Added Boilerplate text 

---

Training/01-Overview.md
Training/02-Markdown.md
Training/03-GitHub-Discussions.md
Training/README.md

Added GitHub Training Content

---

Business-Plan/05-Our-Values/Documents/Charter/Draft-Charter.md

training purpose - please allow me to make this change Stephen

I added a dot as part of training

---

Training/01-Committs.md
Training/01-Overview.md

Replace Overview with Commit Lesson

Replace Overview with Commit Lesson

---

Training/01-Commits.md

Rename file name and formatting updates

Rename file name and formatting updates

---

Training/README.md

Updated link to commit lesson

---

Documents/Governance-of-Business-Relations/OccamFi/AMA-Questions.md
Documents/Governance-of-Business-Relations/OccamFi/README.md
Documents/Governance-of-Business-Relations/README.md
Documents/Governance-of-Business-Relations/Surveys/README.md

Creation of Business Governance Section, associated documentation, research and surveys.

Creation of Business Governance Section

---

Documents/Governance-of-Business-Relations/OccamFi/IDO-Preparation-Roadmap-OccamRazer.md

IDO-Preparation-Roadmap-OccamRazer

IDO-Preparation-Roadmap-OccamRazer

---

Documents/Governance-of-Business-Relations/OccamFi/AMA-Questions.md

Added some AMA Questions and context quote from Gov-HOLON meeting of 14th May 2021

Added some AMA Questions

---

Documents/Governance-of-Business-Relations/Surveys/NFT-DAO-Core-Contributor-Survey.md

An amended version of the survey doc that includes the list of questions, so that their visible without having to fill out the actual survey.

Added the list of survey questions

---

Documents/Governance-of-Business-Relations/OccamFi/AMA-Questions.md

John's Question

---

Documents/Governance-of-Business-Relations/OccamFi/AMA-Questions.md

added my (DanMercurius) questions

---

Documents/Governance-of-Business-Relations/OccamFi/AMA-Questions.md

Added the third NewMindflow question.

NewMindflow Questions - 3

---

Documents/Governance-of-Business-Relations/OccamFi/AMA-Questions.md

1. Multiple NFT proposals to Project Catalyst unified to form the single NFT-DAO proposal that the Cardano community voted to fund. How does OccamFi plan to facilitate continued collaboration and funding for NFT-DAO within the Project Catalyst platform?
2. Given the controversy surrounding OccamFi's IDO, what would OccamFi do differently in hindsight? 
3. If given the opportunity, how would OccamFi handle an NFT-DAO IDO? What would OccamFi do the same or differently from their own IDO?

John's Questions
